FROM python:3.6.12-alpine

ENV USER=jenkins
ENV UID=995

RUN adduser \
    --disabled-password \
    --system \
    --gecos "" \
    --home "$(pwd)" \
    --no-create-home \
    --uid "$UID" \
    "$USER"
WORKDIR /app
COPY requirements.txt /app/requirements.txt
RUN pip3 install --no-cache-dir -r requirements.txt
COPY . /app
EXPOSE 80
CMD ["gunicorn", "--bind", "0.0.0.0:80","--timeout", "90", "app:app"]
