FROM python:3.6.12-alpine
RUN adduser -u 995 -s /bin/bash jenkins
WORKDIR /app
COPY requirements.txt /app/requirements.txt
RUN pip3 install --no-cache-dir -r requirements.txt
COPY . /app
EXPOSE 80
CMD ["gunicorn", "--bind", "0.0.0.0:80","--timeout", "90", "app:app"]
